# Generated by Django 5.0.2 on 2024-03-03 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_testing_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_id', models.AutoField(primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('treatment', models.TextField()),
                ('prevention', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='disease_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('nutrition_id', models.AutoField(primary_key=True, serialize=False)),
                ('age_group', models.CharField(max_length=50)),
                ('feeding_method', models.CharField(max_length=100)),
                ('breast_milk_composition', models.TextField()),
                ('formula_milk_composition', models.TextField()),
                ('introduction_of_solids', models.TextField()),
                ('recommended_diet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PolioDetails',
            fields=[
                ('polio_id', models.AutoField(primary_key=True, serialize=False)),
                ('dose_1_date', models.DateField(blank=True, null=True)),
                ('dose_2_date', models.DateField(blank=True, null=True)),
                ('dose_3_date', models.DateField(blank=True, null=True)),
                ('booster_dose_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('vaccine_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('disease_targeted', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('storage_requirements', models.CharField(max_length=100)),
                ('efficacy', models.FloatField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(max_length=50)),
                ('date_of_approval', models.DateField()),
                ('distribution_status', models.CharField(max_length=50)),
                ('country_region_approval', models.CharField(max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vaccin_images/')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='testing',
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Base.parent'),
        ),
        migrations.AddField(
            model_name='poliodetails',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polio_details', to='Base.child'),
        ),
        migrations.AddField(
            model_name='vaccinestatus',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.child'),
        ),
        migrations.AddField(
            model_name='vaccinestatus',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.vaccine'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='child',
            field=models.ManyToManyField(related_name='vaccines', through='Base.VaccineStatus', to='Base.child'),
        ),
        migrations.AddField(
            model_name='child',
            name='vaccine',
            field=models.ManyToManyField(related_name='children', through='Base.VaccineStatus', to='Base.vaccine'),
        ),
    ]
