# Generated by Django 5.0.2 on 2024-03-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_child_disease_doctor_hospital_nutrition_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='nutrition_name',
            field=models.CharField(default='Nutrition Name Unavailable', max_length=100),
        ),
    ]
