# Generated by Django 5.0.2 on 2024-03-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_nutrition_nutrition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
