# Generated by Django 5.0.2 on 2024-03-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_day_remove_doctor_days_in_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='days_in_hospital',
        ),
        migrations.AddField(
            model_name='doctor',
            name='days_in_hospital',
            field=models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=50, null=True),
        ),
    ]
