# Generated by Django 5.0.2 on 2024-03-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_remove_doctor_days_in_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='days_in_hospital',
        ),
        migrations.AddField(
            model_name='doctor',
            name='days_in_hospital',
            field=models.ManyToManyField(to='Base.day'),
        ),
    ]
