# Generated by Django 5.0.2 on 2024-03-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0016_alter_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='breast_milk_composition',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='formula_milk_composition',
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='introduction_of_solids',
            field=models.TextField(blank=True, default='Not applicable', null=True),
        ),
    ]
