# Generated by Django 5.0.2 on 2024-03-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_remove_nutrition_breast_milk_composition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='dp',
            field=models.ImageField(blank=True, default='default_dp.jpg', null=True, upload_to='parent_images/'),
        ),
    ]
