# Generated by Django 5.0.2 on 2024-03-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0018_parent_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_sex',
            field=models.CharField(default='Undefined', max_length=10),
        ),
        migrations.AlterField(
            model_name='child',
            name='vaccine',
            field=models.ManyToManyField(blank=True, null=True, related_name='children', through='Base.VaccineStatus', to='Base.vaccine'),
        ),
    ]
