# Generated by Django 5.0.2 on 2024-03-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0020_alter_child_child_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
