# Generated by Django 5.0.2 on 2024-03-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0021_child_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinestatus',
            name='date_of_vaccination',
            field=models.DateField(blank=True, null=True),
        ),
    ]
