# Generated by Django 5.0.2 on 2024-03-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0023_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(default='default_hospital.jpeg', upload_to='hospital_images/'),
        ),
    ]
